# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 解雇されるし豊富温泉で湯治するか
email: tomoharu.kawata@outlook.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/HotSpringCure" # the subpath of your site, e.g. /blog
lang: "ja"
url: https://toxumuharu.github.io/" # the base hostname & protocol for your site
twitter_username: HaruShoots
# github_username: toxumuharu
# disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  style: compressed


images: '/assets/images'
